// <auto-generated />
using HavaDurumu.Api.ContextLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HavaDurumu.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HavaDurumu.Api.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Celcius")
                        .HasColumnName("CELCIUS");

                    b.Property<string>("City")
                        .HasColumnName("CITY");

                    b.Property<int>("Humidity")
                        .HasColumnName("HUMIDITY");

                    b.Property<string>("Status")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("WEATHERFORECAST");
                });
#pragma warning restore 612, 618
        }
    }
}
